struct hochzeitstag {
  int period; char name[24]; char text[666];
};

#define STANDESAMTLICH 0
#define KIRCHLICH 1
const char *dates[2][25];
struct hochzeitstag hochzeitstage[25] = {
  {1, "Die Papierhochzeit", "Der Grundgedanke hinter dieser Bezeichnung ist, dass die Ehe noch frisch und d\xfc" "nn wie Papier ist. Zwar f\xfc" "hlen sich die meisten Paare schon sehr stark verbunden, doch k\xf6" "nnten \"widrige Umst\xe4" "nde\" die Ehe immer noch aufl\xf6" "sen wie N\xe4" "sse das Papier.\n Die Papierhochzeit ist einer der Hochzeitstage der meist in trauter Zweisamkeit gefeiert wird, um die Erinnerungen an die gemeinsame Zeit und den Tag der Trauung noch einmal wach zurufen."},
  {2, "Die Baumwollenhochzeit", "Das Brautpaar hat die ersten H\xf6" "hen und Tiefen der Ehe hinter sich und kann mit diesen gut umgehen. Dadurch festigt sich der neue Bund und das Paar f\xfc" "hlt sich geborgen. Der Name Baumwollhochzeit entstand, weil Baumwolle weich ist, gut w\xe4" "rmt und damit die Geborgenheit in einer guten Ehe darstellt."},
  {3, "Die Lederne Hochzeit", "Leder ist widerstandsf\xe4" "hig und verl\xe4" "sslich. Daher soll bei der Ledernen Hochzeit gefeiert werden, dass sich die Ehepartner kennen und lieben - sowohl die sch\xf6" "nen als auch die weniger sch\xf6" "nen Seiten. Sie haben gelernt mit den Stimmungen des Partners umzugehen und den anderen so zu nehmen, wie er ist."},
  {4, "Die Seiden Hochzeit", "Ein nicht all zu bekannter Hochzeitstag und trotzdem wichtig genug um genannt zu werden. Dieser Tag wird gerne im kleinen Kreis verbracht und dazu genutzt, sich die Hochzeitsfotos noch einmal anzuschauen und ein bisschen in Erinnerung zu schwelgen. Falls doch gr\xf6" "\xdf" "er gefeiert wird, bietet es sich an Seidenelemente mit in die Dekoration einzubauen. Eine Seidene Tischdecke mit passenden Servietten aus Seide und um alles abzurunden ein paar h\xfc" "bsche Seidenblumen, ganz getreu dem Motto."},
  {5, "Die H\xf6" "lzerne Hochzeit", "Holz ist stark, best\xe4" "ndig und stabil. Nach f\xfc" "nf Ehejahren wird in vielen F\xe4" "llen auch die Ehe so sein. Das ist die Aussage der H\xf6" "lzernen Hochzeit. So wie das Holz soll auch die Ehe in den n\xe4" "chsten Jahren immer weiter wachsen und immer kr\xe4" "ftiger werden. Die H\xf6" "lzerne Hochzeit ist das erste runde Jubil\xe4" "um der Hochzeitstage."},
  {6, "Die Zinn Hochzeit", "Wie Zinn sollte auch die Ehe von Zeit zu Zeit ein bisschen aufgeputzt und poliert werden. Das verleiht neuen Glanz und neuen Schwung. Weil Zinn sehr weich und  formbar ist, steht es sinnbildlich  f\xfc" "r die Formbarkeit der Ehe. Nutzen Sie diesen Tag und probieren sie etwas Neues aus. Beispielsweise festigen Fallschirmspr\xfc" "nge, Wanderurlaube oder andere Aktivit\xe4" "ten das Miteinander und bringen Spa\xdf" " und au\xdf" "ergew\xf6" "hnliche Erinnerungen."},
  {7, "Die Kupferne Hochzeit", "Die Ehe gl\xe4" "nzt nach sieben Jahren nicht mehr so neu, wie am ersten Tag. Aber unter der Schicht der Jahre liegt noch immer das \"Sch\xf6" "ne\" und \"Wahre\". Aus der Verliebtheit ist eine innige Liebe geworden, die sich als Patina auf die Ehe gelegt hat."},
  {8, "Die Blecherne Hochzeit", "Nach acht Jahren ist in vielen Ehen der Alltag eingezogen. Das ist keineswegs etwas Negatives, auch wenn es im ersten Moment so klingt. Man versteht sich auch ohne Sprache, wei\xdf" ", wie man miteinander umgehen muss, was man geben und was man nehmen kann und aus dem Ehepaar ist ein eingespieltes Team geworden."},
  {10, "Die Rosenhochzeit", "Ein ganzes Jahrzehnt verheiratet, damit ist die Rosenhochzeit einer der wichtigen Hochzeitstage. Seite an Seite mit einem anderen Menschen. Da erlebt man viel Gutes und muss auch mal schlechte Tage teilen. Da ist es Zeit sich zu zeigen, dass man sich liebt.\nUnd wie geht das besser und romantischer als mit der Blume der Liebe, der Rose?\nBl\xfc" "te und Dornen symbolisieren von der Liebe ber\xfc" "hrte Momente. Die duftende Bl\xfc" "te zeigt Reife und Sch\xf6" "nheit, ihr Stiel mit den Dornen symbolisiert Zeiten in denen man auf Konflikte und belastete Zeiten zur\xfc" "ckschauen muss."},
  {11, "Die Stahlhochzeit", "Elf Jahre verheiratet, da halten Mann und Frau im Volksmund so fest zusammen wie Kruppstahl. Der starke Zusammenhalt des Paares wird auch in den weiteren Ehejahren den Hochs und Tiefs standhalten. Stahl wird oft auch als Grundger\xfc" "st beim Hausbau verwendet.\nUnd genauso spiegelt die Stahlhochzeit die Standfestigkeit und Stabilit\xe4" "t der Ehe wider, die ihrerseits auch auf guten Grund gebaut ist."},
  {12, "Die Petersilienhochzeit", "Dieses Datum ist f\xfc" "r viele Ehepaare etwas Besonderes. Da die Petersilienhochzeit die Halbzeit zur Silberhochzeit markiert, wird sie von vielen Paaren gerne gefeiert. Die Petersilie steht im \xfc" "bertragenden Sinne f\xfc" "r das Gedeihen der Ehe in den kommenden Jahren, sie soll schmackhaft und gr\xfc" "n bleiben."},
  {13, "Veilchenhochzeit", "Der 13. Hochzeitstag ist auch unter den Namen Maigl\xf6" "ckchen Hochzeit und Spitzenhochzeit bekannt. Wie auch immer man ihn bezeichnet, all die Namensgeber haben eines gemeinsam:\nSie zeigen, dass die Ehe verletzlich ist wie eine Pflanze oder so empfindlich wie feine Spitze. Sie muss gepflegt werden."},
  {14, "Elfenbeinhochzeit", "Elfenbein ist ein kostbares und rares Gut. Auch viele Ehen halten den Irrungen und Wirrungen der Zeit nicht Stand. Paare die diesen Tag erreicht haben, sollten ihre Ehe weiterhin pflegen wie das kostbare Elfenbein. Zwar ist das Elfenbein ein Symbol f\xfc" "r H\xe4" "rte und Unzerst\xf6" "rbarkeit, es muss aber, ebenso wie eine gute Ehe, stets gepflegt werden."},
  {15, "Die Gl\xe4" "serne Hochzeit", "Dieser Tag steht nicht etwas f\xfc" "r Zerbrechlichkeit, im Gegenteil. Die Gl\xe4" "serne Hochzeit zeigt, dass die Eheleute fest miteinander verbunden sind. Man wei\xdf" ", was der andere denkt und f\xfc" "hrt."},
  {20, "Porzellan Hochzeit", "In 20 Jahren Ehe kann im Streit auch mal der ein oder andere Teller aus Porzellan Spr\xfc" "nge bekommen oder sogar zu Bruch gehen. Daher wird dieses Jubil\xe4" "um in manchen Regionen auch die Dornenhochzeit genannt.\nIm Alltag f\xe4" "llt in jeder Beziehung mal ein Wort, das einen kleinen Riss oder Stich hinterlassen kann. Wie jeder aber wei\xdf" " sind Porzellan und Dornen so stabil, dass sie nicht zerbrechen. Ebenso h\xe4" "lt die Ehe nach 20 Jahren viel aus und bleibt fest und stabil."},
  {25, "Die Silberhochzeit", "Eines der wohl wichtigsten Hochzeitstage \xfc" "berhaupt ist die Silberhochzeit. Die Ehe dauert nun schon ein viertel Jahrhundert an. Wie altes Silber hat sie ihren bleibenden Wert unter Beweis gestellt. Viele Eheleute feiern diesen Tag geb\xfc" "hrend mit Verwandten, Bekannten und Freunden, die sie in ihrer bisher 25-j\xe4" "hrigen Ehe begleitet haben."},
  {30, "Die Perlenhochzeit", "Nach 30 Jahren Ehe feiert man die Perlenhochzeit. Die aneinanderreihenden Perlen einer Kette stehen symbolisch f\xfc" "r die aneinanderreihenden Tage der Ehe. Jede Perle, jeder Tag, hat eine eigene Geschichte, so wurden Kinder geboren, vielleicht ein Haus gebaut, das Paar hatte gute und schlechte Zeiten."},
  {35, "Die Leinen Hochzeit", "Nach 35 Jahren hat die Ehe gezeigt hat, das sie so unzerrei\xdf" "bar ist wie gutes Leinen, aber auch flexibel genug um nicht immer nur starren Regeln zu folgen Das traditionelle Geschenk zu diesem Hochzeitstag ist W\xe4" "sche."},
  {40, "Die Rubin Hochzeit", "Der Edelstein Rubin, als Namensgeber, wird als Stein des Lebens und der Liebe bezeichnet. Man sagt ihm nach, dass er die Kr\xe4" "fte aller anderen Edelsteine vereint.\nRot steht dabei f\xfc" "r das Feuer der Liebe, das auch nach 40 Ehejahren noch immer leuchtet. Traditionell wird am Tag der Rubinhochzeit der Ehering der Frau mit einem roten Rubin veredelt."},
  {45, "Die Messinghochzeit", "ie Bedeutung dieses Tages leitet sich von den Eigenschaften des Metalls ab. Messing ist schwer, extrem haltbar, aber dennoch dehnbar.\nGenauso verh\xe4" "lt es sich auch mit der Ehe nach 45 Jahren. Sie wiegt schwer und ist doch noch flexibel. Und nach 45 Jahren weit sie auch eine gewisse Haltbarkeit auf, viele Paar werden sich jetzt nicht mehr trennen, egal was jetzt noch kommen mag."},
  {50, "Die Goldene Hochzeit", "Wow, 50 Jahre verheiratet, ein halbes Jahrhundert Ehemann und Ehefrau. Was liegt da n\xe4" "her als dieses Jubil\xe4" "um mit einem der edelsten Metalle der Welt zu feiern. Viele Paare erneuern nach 50 Jahren ihr Ehegel\xf6" "bnis in der Kirche und feiern gemeinsam mit Verwandten, Bekannten und Freunden.\nDa sich die meisten Jubilare bei ihrer Goldenen Hochzeit schon in gehobenen Alter befinden, wird das Fest meist von den Kindern und Enkeln ausgerichtet. Die Jubilare d\xfc" "rfen sich dabei ihre Tr\xe4" "ume, die bei Ihrer Hochzeitsfeier zu kurz kamen, erf\xfc" "llen. Damit ist die Goldene Hochzeit einer der wichtigsten Hochzeitstage. Ein wundervolles Geschenk ist ein Zweitring zur Ehe."},
  {55, "Die Juwelenhochzeit", "Am 55. Hochzeitstag wird die Juwelenhochzeit gefeiert. Als Juwelen werden geschliffene Edelsteine bezeichnet. Auch die Ehe hat sich im Laufe der Jahre abgeschliffen. Ecken und Kanten sind poliert. Jetzt zeigt die Ehe, wie die Steine, ihre Kraft und Reinheit. Ein Juwel ist etwas wertvolles. Er ist wertbest\xe4" "ndig und nahezu unzerst\xf6" "rbar. Ebenso wie die Ehe, die mehr als ein halbes Jahrhundert \xfc" "berstanden hat."},
  {60, "Die Diamanthochzeit", "Die Diamantene Hochzeit ist ein ganz besonderes und au\xdf" "ergew\xf6" "hnliches Jubil\xe4" "um. Diamantene Hochzeit, das bedeutet 60 Jahre Ehe. 60 Jahre, in denen Kinder, Enkelkinder und Urenkelkinder geboren und H\xf6" "hen und Tiefen bew\xe4" "ltigt wurden. Bedingungslose Liebe, Treue und Zusammenhalt sind die Faktoren, die eine solch lange Ehe erst erm\xf6" "glichen."},
  {65, "Die Eiserne Hochzeit", "Genau wie das Eisen h\xe4" "lt die Ehe nach 65 Jaher zahlreichen Angriffen stand, ohne an Substanz zu verlieren. Das Ehepaar hat gute und schlechte Zeiten durchstanden, den Kampf gegen Krankheiten aufgenommen und Bew\xe4" "hrungsproben \xfc" "berstanden."},
  {70, "Die Gnadenhochzeit", "Warum sich dieser Hochzeitstag „Gnadenhochzeit“ nennt, ist nicht \xfc" "berliefert. Auf jeden Fall ist es einer der ganz besonderen Hochzeitstage. Vielleicht, weil nach so langer Zeit nicht nur die Ehe in die Jahre gekommen ist, sondern auch das Ehepaar? Der Begriff Gnade wird fast ausschlie\xdf" "lich mit dem Christentum und der damit verbundenen Gottesgnade in Verbindung gebracht und bedeutet hier \"wohlwollend\"."},
};
